# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3dfa395e101ea4cfbd44209ef4fb5213c08cf2b78783a18710de7e532f21f6a3c235ed1d925f01b0b9d75e81f407ee20539d72a83f92a07ee38d834bdf4bffd

test:
  secret_key_base: 49e16395df9d5d1783ea30ad8ef4743355704990c830a6790fbc54484040f4ec51c91ea9c56c24a005bbcb73495dfef89165e96054230238150ac78221ada804

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
